[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
[tool.poetry.dependencies]
fire = "==0.2.1"
python = "^3.7"
six = "==1.13.0"
sqlalchemy = "==1.3.11"
termcolor = "==1.1.0"
